# Generated by Django 2.0.3 on 2018-04-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180403_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='f_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='feedback.Feedback'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
