# Generated by Django 2.0.3 on 2018-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20180403_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='negative',
            new_name='q1',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='positive',
            new_name='q2',
        ),
        migrations.AddField(
            model_name='feedback',
            name='q3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='q4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='q5',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='q6',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
